#!/usr/bin/env bash
# Install Nginx with server 0x01 config
#+ add HTTP header named X-Served-By $HOSTNAME

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=xJJsoquu70o/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart

fab -f 2-do_deploy_web_static.py do_deploy:archive_path=versions/web_static_20221001153050.tgz -i b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAyRb493gVEiPhhAlDr1pXDyDPwVRPnGHYt5z9CujwmWPmQRS6rZph
nut16rBWaefU9LCEGw6zw3glrQVEH8vWnrW5VVXHCvpfuNZrZeZTwKKiaDcz0sJNmabL8t
8wR8uhzPWRUa0PKmpm6Q2tAc726qRXT5hFJt6O3zVYFfz5tTXqcIfSriK12JrfXl3fVaCS
Fkh81tWL5lrcaR8oVcBehC+FuKC/ArcR0GTxdKb2zaXpgjn7VOytGY4fsPOxYV3UnsDr97
jNxl2Bc2o0br7TJXbrDHo32CSvBoeDv4VQgW0SPHX0cLiz1lq5KdfVQY/nOF0XE62A4oXZ
+L2VKXi8CvFcSOkLeM706qEL1JJUuiDVH3HcBgU/VBnb/Mr6h2LZXm9rapUEUKHLLm6pQV
4zjNZxkgiXLkhVz5h9nLqtS9GTpI0T0Q6IAByxD888DYg65V3T8yVoggU/W3PjQ/ADWvbc
23ahPVXXEGaFl9SeWiymsvyIGC8Fn/8hPkjpVgz9AAAFkKvnC++r5wvvAAAAB3NzaC1yc2
EAAAGBAMkW+Pd4FRIj4YQJQ69aVw8gz8FUT5xh2Lec/Qro8Jlj5kEUuq2aYZ7rdeqwVmnn
1PSwhBsOs8N4Ja0FRB/L1p61uVVVxwr6X7jWa2XmU8Ciomg3M9LCTZmmy/LfMEfLocz1kV
GtDypqZukNrQHO9uqkV0+YRSbejt81WBX8+bU16nCH0q4itdia315d31WgkhZIfNbVi+Za
3GkfKFXAXoQvhbigvwK3EdBk8XSm9s2l6YI5+1TsrRmOH7DzsWFd1J7A6/e4zcZdgXNqNG
6+0yV26wx6N9gkrwaHg7+FUIFtEjx19HC4s9ZauSnX1UGP5zhdFxOtgOKF2fi9lSl4vArx
XEjpC3jO9OqhC9SSVLog1R9x3AYFP1QZ2/zK+odi2V5va2qVBFChyy5uqUFeM4zWcZIIly
5IVc+YfZy6rUvRk6SNE9EOiAAcsQ/PPA2IOuVd0/MlaIIFP1tz40PwA1r23Nt2oT1V1xBm
hZfUnlosprL8iBgvBZ//IT5I6VYM/QAAAAMBAAEAAAGBAI/govQVdCYNjC63njkZz06gsG
VoWKnQjIobhiXHM1bc1oNcPJE3838Mg8sOrlWKLaGBppPhehdyoKpiKTMC2qWl6lw3Snn9
WH3c1O0M1oHvG3qrfKXgpjs4z5YPwPCtrzAByB8DTuWPSeCYC2BO3/ZU7a+iiF/eP6VO+p
6I6XWRhRNM6x3y8d9wOD/BtKkEgWH2LXRdSILiIfAI/ggU4st7YRcP1Hsx10oe33ASgmXz
vtaRe9Vwng251cz7H8BFrDR/UK+DHyZnGLmVMhuBYt0ZsJTDrhxK/8BnJHnlJHESG577vO
l1ZqQOnsc1eLnnQcC5bXhfJlvJakTDH2otwKzMKv85r7mXCnU8dqfbrKRKu1lm9aSVBaXM
i9y5/9/a3rZv0BmPvg9shU6KdnhfOC9BE8FjG7BX4xiAC8R/FRFL0JM2ZkfFX9G9DV4W0i
Oi43uhNpbhD1RNMplSn4vsl+LDsEV9PJ9dDZhC4j44djBRQtFxXvCEePC9rwuLKlC69QAA
AMEA1kgHftIOyhQ+X8JfTUchpSeIQPZk7B4f7ovPBtskctuWQ5vydqko9LFsC5PGTD5ajP
8mgKt60JSDldQ+Y1vNC21PFnBzrFRFUmmVVqPgzFq8nVFaMTKE7aB16R33Uz9kedJFtD7m
E/Hl48i5/tTU6DA2FA3aZC2/41mmSPXYHIFPuu+s0nWPCyEFP46cD7wa35VuOPeIBRT77s
YXwdApLZ2x+uv74k8i/u8EwQy4775emsn6JqoRPt0Z7dRwMwojAAAAwQD4h/jopZzoosTU
B+7pd1rRyq/JsCLj0EFvrFz27teLJ66lCrjQ51uim02KOnQZx1ueq3i6xWrH3RtOiN7Pxd
GwRChzeOKbdDAWP6tW9864u1JNFnSzj2zwAP5YezE/Ut0ldDlzvK+BBFMCagiPSZY2kYg+
UNzNf7klgHH1gtob1Ojou1O8xfIbg5vT4u6M+RnJxKmWpUtU9dD61VE5vkCgdGim/wKS+8
0s1LfQHbWRPoeyIfKJbJ6CevMCzL6gh4sAAADBAM8iBMgBL/kvC26J1olklr0oWrGs3QtM
FI88N1CKpTy0xPSF0M2gX1+V+nzivhAHgXvsHwRlZMDsT5XlAMnidnfvSlziQ0gSdTqhl3
+dyRYNmWEnO4++n2O9v8QhVXRE5//AkCCLmyDIiQI0i6DhIlwezH+c0WG9yfWkLBnwUFEB
qb1p5GI/JJNZ0WpvzFyD+ZhEVyqsfMZaljZbQB4TtnhX17KGDdPwMjSV4RnC0dQ6kyTt0k
BN91eoAb3tT0WOlwAAABdpbWFjQGlNYWMtZGUtaW1hYy5sb2NhbAEC -u ubuntu