#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

load_balancer="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b
backend load_b\n
\tbalance roundrobin
\tserver 5066-web-01 3.229.138.169:80 check
\tserver 5066-web-02 44.197.103.2365:80 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart